from app.base.models import BaseModel, FindQuery, Page
from app.utils import Positive
from typing import Protocol

class SupportsModelPersistance[Model: BaseModel, Query: FindQuery](Protocol):
    async def add(self, model: Model) -> Model: ...
    async def find(self, query: Query) -> Page[Model, Query] | None: ...
    async def find_by_id(self, id: Positive[int]) -> Model | None: ...
    async def update(self, id: Positive[int], model: Model) -> Model: ...
    async def delete(self, id: Positive[int]) -> Model: ...
    async def upsert(self, model: Model) -> Model: ...
